(** * FindNode Specification and Proof

    Proves that the C++ [Node::findNode] function refines the functional
    [findNode] from [RBTree.v].

    [findNode] is the simplest operation to verify: it is read-only
    (no allocation, no mutation), making it an ideal warm-up for BRiCk's
    weakest-precondition calculus.

    == C++ function under verification ==

    [[[
    static Node* findNode(Key k, Node *n) {
      Node *curr = n;
      while (curr != nullptr) {
        if (k < curr->key)        curr = curr->left;
        else if (curr->key < k)   curr = curr->right;
        else return curr;
      }
      return nullptr;
    }
    ]]]

    == Proof strategy ==

    The C++ version uses a while loop; the Coq spec uses structural
    recursion. We prove equivalence via a loop invariant and [wp_while_inv].

    Loop invariant -- holds before each evaluation of the loop condition:

      Exists curr_p t_curr,
        _local rho "curr" |-> ptrR<_Node> 1$m curr_p **
        curr_p |-> treeR q t_curr **
        [| findNode k t = findNode k t_curr |] **
        (curr_p |-> treeR q t_curr -* n |-> treeR q t)

    The invariant holds four resources:

    1. [_local rho "curr" |-> ...]: the local variable [curr] stores pointer
       [curr_p].

    2. [curr_p |-> treeR q t_curr]: the current position in the tree.
       We OWN the subtree at [curr_p] so we can unfold it to access fields
       ([curr->key], [curr->left], [curr->right]).

    3. [[| findNode k t = findNode k t_curr |]]: the functional spec's
       [findNode] agrees between the original tree and the current subtree.

    4. [(curr_p |-> treeR q t_curr -* n |-> treeR q t)]: the magic wand
       ("zipper") -- given back the subtree at [curr_p], reconstruct the
       full tree at [n]. This captures all the ancestor nodes' fields and
       sibling subtrees encountered during the traversal.

    Each iteration unfolds [treeR] at [curr_p], reads [curr->key],
    branches on the comparison, and descends into a child.
    The wand is extended by composing: the old wand + the fields of the
    current node + the sibling subtree.

    == Approach ==

    This file uses ONLY the open-source BRiCk core library
    ([skylabs.lang.cpp.*]), NOT the proprietary [skylabs.auto] package.
    The spec is constructed manually with [SFunction] and the proof
    obligation is stated using [func_ok] directly.

    == Dependencies ==

    - Functional correctness lemmas: [RBTree.v] (zero [Admitted])
    - Representation predicate: [TreeRep.v]
    - C++ AST: [map_int_int_cpp.v] (generated by cpp2v, ~96K lines)
*)

From Coq Require Import ZArith Bool Lia.

Require Import daedalus_rb.RBTree.

(** ** Directional recursion lemmas

    These characterize [findNode]'s branching behavior and are used
    directly in the loop body proof to re-establish the invariant.

    Proven before BRiCk imports to avoid ssreflect [rewrite] conflict. *)

(** If [k < kn], [findNode] recurses left. *)
Lemma findNode_lt : forall k c l kn vn r,
  (k < kn)%Z ->
  findNode k (Node c l kn vn r) = findNode k l.
Proof.
  intros k c l kn vn r Hlt. simpl.
  destruct (k <? kn)%Z eqn:E; [reflexivity |].
  apply Z.ltb_ge in E. lia.
Qed.

(** If [kn < k], [findNode] recurses right. *)
Lemma findNode_gt : forall k c l kn vn r,
  (kn < k)%Z ->
  findNode k (Node c l kn vn r) = findNode k r.
Proof.
  intros k c l kn vn r Hgt. simpl.
  destruct (k <? kn)%Z eqn:E1.
  - apply Z.ltb_lt in E1. lia.
  - destruct (kn <? k)%Z eqn:E2; [reflexivity |].
    apply Z.ltb_ge in E2. lia.
Qed.

(** Neither [k < kn] nor [kn < k] implies [k = kn]. *)
Lemma findNode_eq_key : forall k kn : Z,
  ~ (k < kn)%Z -> ~ (kn < k)%Z -> k = kn.
Proof. lia. Qed.

(** ** BRiCk imports (open-source core library only)

    After pure lemmas to avoid ssreflect [rewrite] conflict.

    Uses [skylabs.lang.cpp.cpp] which re-exports:
    - [skylabs.lang.cpp.syntax]: C++ AST types
    - [skylabs.lang.cpp.semantics]: operational semantics
    - [skylabs.lang.cpp.logic]: wp axioms ([func_ok], [wp_func],
      [wp_while_inv], [wp_if], [wp_seq], etc.)
    - [skylabs.lang.cpp.specs]: [SFunction], spec notations
      ([\arg], [\prepost], [\post])
    - [skylabs.lang.cpp.parser]: translation unit, [genv_compat] *)

Require Import skylabs.lang.cpp.cpp.
Require Import skylabs.iris.extra.proofmode.proofmode.
Import cQp_compat.

Require Import daedalus_rb.TreeRep.
Require Import daedalus_rb.map_int_int_cpp.

(** ** Spec and proof section *)

Section with_Sigma.
Context `{Sigma : cpp_logic} `{MOD: map_int_int_cpp.source ⊧ σ}.

(** *** Null pointer helper

    [nullptr] cannot represent a non-leaf tree. Used in the loop exit
    case to conclude [t_curr = Leaf] when [curr_p = nullptr].

    [treeR]'s Node case includes [structR _Node_name q], which implies
    [nonnullR] -- contradicting [nullptr].

    TODO: Prove with Iris tactics once we have the proof infrastructure
    working. For now [Admitted]. *)
Lemma treeR_null q' t' : nullptr |-> treeR q' t' |-- [| t' = Leaf |].
Proof.
  destruct t'.
  - rewrite treeR_leaf. auto.
  - rewrite treeR_node.
    (* Node case: structR _Node_name q' implies nonnullR,
       contradicting nullptr. Needs manual Iris proof. *)
Admitted.

(** *** Function specification

    [findNode] is a static method on [DDL::Map<int,int>::Node], so
    there is no [\this] argument -- both parameters are explicit.

    The tree is borrowed via fractional permission [q] ([\prepost] frame):
    unchanged across the call.

    Return value: [nullptr] when key absent, non-null when present.

    Constructed manually with [SFunction] (replacing the proprietary
    [cpp.spec] command from [skylabs.auto]).

    Types from the cpp2v-generated AST ([map_int_int_cpp.v]):
    - Return type: [Tptr _Node] (= [t711] in AST)
    - Param types: [Tint] for [k], [Tptr _Node] for [n]
    - Calling convention: [CC_C], arity: [Ar_Definite] *)

Definition findNode_spec : function_spec :=
  SFunction (cc:=CC_C) (ar:=Ar_Definite) (Tptr _Node) (Tint :: Tptr _Node :: nil)
    (cpp_spec (ar:=Ar_Definite) (Tptr _Node) (Tint :: Tptr _Node :: nil)
      (\arg{k} "k" (Vint k)
       \arg{n} "n" (Vptr n)
       \prepost{q t} n |-> treeR q t
       \post{ret}[Vptr ret]
         [| match findNode k t with
            | None   => ret = nullptr
            | Some _ => ret <> nullptr
            end |])).

(** *** C++ function body (transcribed from cpp2v AST)

    The function body is transcribed from [map_int_int_cpp.v] lines
    93219-93258. [findNode] is a static method ([Dmethod n12334 true]),
    so [static_method] converts the [Method] to a [Func] by:
    - dropping the class/qualifier info
    - wrapping [UserDefined body] as [Impl body]

    We inline the resulting [Func] directly rather than extracting it
    from the translation unit, because the AST's local definitions
    ([n12334], [t711]) are not exported.

    The types used match the AST exactly:
    - [Tptr _Node] = [t711] = [Tptr (Tnamed n4041)]
    - [Tint] = key type
    - Field accesses use core [Emember] with [Nid "field_name"] directly
      (not the parser's [Field] wrapper which isn't in scope here) *)

#[local] Open Scope pstring_scope.
Definition findNode_body : Stmt :=
  Sseq (
    (Sdecl (
      (Dvar "curr" (Tptr _Node)
        (Some
          (Ecast Cl2r (Evar "n" (Tptr _Node))))) :: nil)) ::
    (Swhile None
      (Ebinop Bneq
        (Ecast Cl2r (Evar "curr" (Tptr _Node)))
        (Ecast (Cnull2ptr (Tptr _Node)) Enull) Tbool)
      (Sseq (
        (Sif None
          (Ebinop Blt
            (Ecast Cl2r (Evar "k" Tint))
            (Ecast Cl2r
              (Emember true
                (Ecast Cl2r (Evar "curr" (Tptr _Node)))
                (Nid "key") false Tint)) Tbool)
          (Sexpr
            (Eassign (Evar "curr" (Tptr _Node))
              (Ecast Cl2r
                (Emember true
                  (Ecast Cl2r (Evar "curr" (Tptr _Node)))
                  (Nid "left") false (Tptr _Node)))
              (Tptr _Node)))
          (Sif None
            (Ebinop Blt
              (Ecast Cl2r
                (Emember true
                  (Ecast Cl2r (Evar "curr" (Tptr _Node)))
                  (Nid "key") false Tint))
              (Ecast Cl2r (Evar "k" Tint)) Tbool)
            (Sexpr
              (Eassign (Evar "curr" (Tptr _Node))
                (Ecast Cl2r
                  (Emember true
                    (Ecast Cl2r (Evar "curr" (Tptr _Node)))
                    (Nid "right") false (Tptr _Node)))
                (Tptr _Node)))
            (Sreturn_val
              (Ecast Cl2r (Evar "curr" (Tptr _Node)))))) :: nil))) ::
    (Sreturn_val
      (Ecast (Cnull2ptr (Tptr _Node)) Enull)) :: nil).

Definition findNode_func : Func :=
  {| f_return := Tptr _Node
   ; f_params := ("k", Tint) :: ("n", Tptr _Node) :: nil
   ; f_cc := CC_C
   ; f_arity := Ar_Definite
   ; f_exception := exception_spec.MayThrow
   ; f_body := Some (Impl findNode_body) |}.
#[local] Close Scope pstring_scope.

(** *** Proof obligation

    [func_ok tu f spec] asserts:
    1. Type agreement: [type_of_spec spec = type_of_value (Ofunction f)]
    2. For all postconditions [Q] and argument values [vals]:
       [spec.(fs_spec) vals Q -* wp_func tu f vals Q]

    This is the manual equivalent of [verify[source] findNode_spec]
    from the proprietary [skylabs.auto] package. *)

Lemma findNode_ok :
  |-- func_ok map_int_int_cpp.source findNode_func findNode_spec.
Proof using MOD.
  rewrite /func_ok.
  iSplit.
  - (** Type agreement: [type_of_spec findNode_spec =
         type_of_value (Ofunction findNode_func)].
         Should reduce to equality of function types. *)
    iPureIntro. reflexivity.
  - (** Spec implies wp. *)
    iIntros "!>" (Q vals) "Hspec".
    iApply wp_func_intro.
    (** Phase B: now inside [wp_func' false tu findNode_func vals Q].
        Next: simpl/cbn to unfold, then process bind_vars + body. *)
Admitted.

End with_Sigma.
